[managed]
managed_node_1 ansible_host=mock_1 ansible_connection=local
managed_node_2 ansible_host=mock_2 ansible_connection=local
managed_node_3 ansible_host=mock_3 ansible_connection=local

[local]
verification_node ansible_host=mock_bvt ansible_connection=local
