- name: Upgrade managed RHEL nodes
  hosts: managed
  gather_facts: false

  tasks:
    - name: "1. Shut down services..."
      ansible.builtin.debug:
        msg: "→ ⛔ {{ inventory_hostname }} :: systemctl stop ..."

    - name: "2. Upgrade packages..."
      ansible.builtin.debug:
        msg: "→ ⏳ {{ inventory_hostname }} :: apt update && apt upgrade ..."

    - name: "3. Start up services..."
      ansible.builtin.debug:
        msg: "→ 🚀 {{ inventory_hostname }} :: systemctl start ..."

- name: Run BVT on localhost
  hosts: local
  gather_facts: false

  tasks:
    - name: "4. Execute BVT..."
      ansible.builtin.shell: npm run test-ci
      ignore_errors: true
      changed_when: false
      register: bvt_result

    - name: "5. Generate BVT report..."
      ansible.builtin.shell: npm run report-ci
      changed_when: false

    - name: "6. Throw on BVT failure..."
      ansible.builtin.fail:
        msg: "→ ❌ [Execute BVT] failed with exit code {{ bvt_result.rc }}. See report for details: https://iamkenos.github.io/ansible-poc"
      when: bvt_result.rc != 0
