- name: Upgrade managed RHEL nodes
  hosts: localhost
  gather_facts: false
  vars:
    managed_nodes:
      - node_1
      - node_2
      - node_3

  tasks:
    - name: "1. Shut down services..."
      ansible.builtin.debug:
        msg: "→ ⛔ {{ item }} :: systemctl stop ..."
      delegate_to: "{{ item }}"
      loop: "{{ managed_nodes }}"

    - name: "2. Upgrade packages..."
      ansible.builtin.pause:
        seconds: 2
        prompt: "→ ⏳ {{ item }} :: apt update && apt upgrade ..."
      delegate_to: "{{ item }}"
      loop: "{{ managed_nodes }}"

    - name: "3. Start up services..."
      ansible.builtin.debug:
        msg: "→ 🚀 {{ item }} :: systemctl start ..."
      delegate_to: "{{ item }}"
      loop: "{{ managed_nodes }}"

    - name: "4. Execute BVT..."
      delegate_to: localhost
      become: false
      ignore_errors: true
      changed_when: false
      vars:
        ansible_connection: local
      command: cmd.exe /c tcshell -workspace "C:\<PATH_TO>\Tosca_Workspaces\First Steps\First Steps.tws" "C:\<PATH_TO>\Tosca_Workspaces\First Steps\ansible-poc.tcs"
      register: bvt_result

    - name: "5. Generate BVT report..."
      debug:
        var: bvt_result.stdout

    - name: "6. Throw on BVT failure..."
      ansible.builtin.fail:
        msg: "→ ❌ [Execute BVT] failed with exit code {{ bvt_result.rc }}. See report for details: https://iamkenos.github.io/ansible-poc"
      when: bvt_result.rc != 0
